-- 코드를 입력하세요
SELECT 
U.USER_ID, 
U.NICKNAME,  
CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2),
CONCAT(SUBSTR(U.TLNO, 1,3), '-', SUBSTR(U.TLNO, 4,4), '-', SUBSTR(U.TLNO, 8,11))
FROM 
    USED_GOODS_USER U
JOIN 
    (SELECT WRITER_ID, COUNT(*)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) > 2) B
ON 
    U.USER_ID = B.WRITER_ID
ORDER BY 
    U.USER_ID DESC;
    
-- SUBSTR(STRING, STARTPOSITION, LENGTH)
-- SUBSTR(STRING, STARTPOSITION) -> 남은 STRING을 전부 추출